services:
    minio:
        container_name: minio
        image: minio/minio:RELEASE.2022-10-08T20-11-00Z
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            - MINIO_ROOT_USER=${MINIO_ROOT_USER}
            - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        entrypoint: sh
        command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
        volumes:
            - ./docker/sensor-storage/minio/data:/export

    postgres:
        container_name: ${POSTGRES_CONTAINER_HOST}
        image: postgres:15
        restart: always
        ports:
            - "5433:5432"
        volumes:
            - ./docker/postgres/init:/docker-entrypoint-initdb.d
            - ./docker/postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    golang:
        container_name: ${GO_CONTAINER_HOST}
        hostname: ${GO_HOST}
        tty: true
        env_file: .env
        build:
            context: .
            dockerfile: ./docker/go/Dockerfile
        volumes:
            - ./src:/go/src/app
        depends_on:
            - "postgres"
        ports:
            - 8086:8000
